[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "fastapi>=0.115.12",
    "parlant>=3.0.2",
    "pydantic>=2.11.9",
    "uvicorn>=0.32.1",
]
